import React from 'react'

import bannerleft from '../images/banner-left_processed.png';
import bannerright from '../images/banner-right_processed.png';
import alisonaffiliate from '../images/alisonaffiliate.PNG';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck } from '@fortawesome/free-solid-svg-icons';
import becomeanaffilate from '../images/becomeanaffilate.PNG';
import becomeanaffilatedesktop from '../images/becomaffiliatedesktop.PNG';
import socialaffiliate from '../images/socialaffiliate.PNG';
import helpaffiliate from '../images/helpaff.PNG';
import learningaffiliate from '../images/learningaffiliate.PNG';

function Affiliates() {



  return (
    //     <div className='m-4 bg-[rgb(255,255,255)]'>
    //         <div className='w-[90%] ml-[5%]'>
    //         <h1 className='text-[rgb(249,157,39)] text-center text-md font-bold mt-6'>Alison Affiliates Programme</h1>
    //         <h2 className='font-semibold  text-[26px] w-[260px]  mt-4 text-center'>Bring New Learners & Earn Money</h2>
    //         <p className='text-center mt-4 w-[82%] ml-[9%]'>Introduce others to Alison and receive 20% of the revenue generated by them. Spread the word of Alison and start earning today!</p>
    //         <div className='bg-[rgb(249,157,39)] text-white text-md font-bold text-center mt-4 p-3 w-[60%] ml-[20%] rounded-full'><a>Become an Affiliate</a></div>
    //   </div>
    //     </div>
    <div className='my-4 bg-white'>

      <div className='w-full w-[288px]  md:w-[500px] mx-auto  py-8 text-center lg:flex  lg:w-[80%] gap-x-4'>
        <div className='flex flex-col gap-y-4 lg:w-[50%]'>
          <h1 className='text-[rgb(249,157,39)] text-center text-[18px] md:text-2xl font-bold mt-6 lg:text-start lg:text-[25px]'>
            Alison Affiliates Programme
          </h1>
          <h2 className='font-black text-[26px] text-center md:mt-4  md:text-[44px] md:flex md:flex-col md:leading-10 md:gap-y-2 lg:text-[32px] lg:text-start lg:leading-0'>
            <span className='block'>Bring New Learners</span>
            <span className='block'>& Earn Money</span>
          </h2>
          <p className='text-sm sm:text-md text-center mt-4 lg:text-start lg:text-[16px] lg:leading-6'>
            Introduce others to Alison and receive 20% of the revenue generated by them. Spread the word of Alison and start earning today!
          </p>
          <div className='bg-[rgb(249,157,39)] text-white text-md font-bold text-center mt-4 p-3 rounded-full mx-auto w-[60%] lg:ml-0'> {/* Centered button */}
            <a href="#">Become an Affiliate</a>
          </div>
        </div>
        <div><img src={alisonaffiliate} /></div>
      </div>


      {/* <div className='bg-[rgb(255,247,237)]'>
    <div>
    <h2 className='font-black text-[22px] text-center'>How The Alison Affiliate Programme Works</h2>
    <div className='w-[30%] m-auto'>
             
        <div className='flex gap-2'>
        <div className='h-8 w-8 rounded-full text-white bg-[rgb(249,157,39)] text-md flex items-center justify-center '>1</div>
        <div><h3>Register</h3><p className='text-[rgb(148,152,153)] leading-tight'>Join the Alison Affiliate programme and <span className='text-[rgb(103,111,117)]'>generate Affiliate Links.</span></p></div>
        </div>
         
        <div>
            <div className='h-8 w-8 rounded-full text-white bg-[rgb(249,157,39)] text-xl text-center'>2</div>
        <div><h3>Invite</h3><p className='text-[rgb(148,152,153)]'>Share your Affiliate Links with others,  <span className='text-[rgb(103,111,117)]'>anywhere on the web..</span></p></div>
        </div>
        <div>
            <div className='h-8 w-8 rounded-full text-white bg-[rgb(249,157,39)] text-xl text-center'>3</div>
        <div><h3>Earn</h3><p className='text-[rgb(103,111,117)]'>Receive 20% of the revenue <span> generated by new learners you bring to Alison.</span></p></div>
        </div>
    </div>
    </div>
  </div>  */}


      <div className='bg-[rgb(255,247,237)] py-14'>

        <h2 className='font-black text-[24px] text-center'>How The Alison Affiliate Programme Works</h2>
        <div className='flex  w-[300px] mx-auto md:w-[40%]  pt-14 lg:flex-col lg:w-[80%]'>
          <div className='w-[16%] flex flex-col gap-y-[74px]  p-2 pt-0 md:p-0 lg:flex-row lg:justify-around lg:w-[97%]'>
            <div className='h-6 w-6 rounded-full text-white bg-[rgb(249,157,39)] text-xl flex items-center justify-center lg:w-11 lg:h-11 lg:text-2xl'>1</div>
            {/* <div className='flex gap-x-2'><span className='h-[6px] w-[6px] text-[rgb(249,157,39)] rounded-full'></span><span></span><span></span><span></span><span></span><span></span></div> */}
            <div className='h-6 w-6 rounded-full text-white bg-[rgb(249,157,39)] text-xl flex items-center justify-center lg:w-11 lg:h-11 lg:text-2xl'>2</div>

            <div className='h-6 w-6 rounded-full text-white bg-[rgb(249,157,39)] text-xl flex items-center justify-center lg:w-11 lg:h-11 lg:text-2xl'>3</div>
          </div>

          <div className='w-[62%] flex flex-col gap-y-6 text-[15px] lg:flex-row lg:flex-row lg:gap-x-12 lg:w-full lg:text-center lg:mx-auto'>
            <div><h3 className='font-black lg:text-xl lg:pl-4'>Register</h3><p className='text-[rgb(148,152,153)] text-[14px] leading-tight lg:text-[18px] lg:p-6 '>Join the Alison Affiliate programme and <span className='text-[rgb(103,111,117)]'>generate Affiliate Links.</span></p></div>


            <div><h3 className='font-black lg:text-xl '>Invite</h3><p className='text-[rgb(148,152,153)] text-[14px] lg:text-[18px] lg:p-4 '>Share your Affiliate Links with others,  <span className='text-[rgb(103,111,117)]'>anywhere on the web..</span></p></div>


            <div><h3 className='font-black lg:text-xl lg:w-[290px]'>Earn</h3><p className='text-[rgb(103,111,117)] text-[14px] lg:text-[18px] lg:p-4'>Receive 20% of the revenue <span> generated by new learners you bring to Alison.</span></p></div>
          </div>

        </div>

      </div>

      {/* <div className='bg-[rgb(248,162,50)] text-center flex'>
          <Image src={bannerleft} className='h-[100px] w-[90px]'/>
          <h3 className='w-[290px] text-white  text-2xl '>Referral Commissions paid out across 100 Countries Annually</h3>
          <Image src={bannerright} className=''/>
        </div> */}
      <div className="bg-[rgb(248,162,50)] text-center flex flex-col items-center lg:flex-row lg:justify-center lg:items-center">

        <div className="flex justify-between w-full ">
          <img src={bannerleft} className="h-[100px] w-[90px] lg:h-auto lg:w-auto mx-2" />
          <h3 className="text-white text-2xl w-full mb-4 lg:mb-0 lg:order-none order-1 lg:w-[290px]">
            Referral Commissions paid out across 100 Countries Annually
          </h3>
          <img src={bannerright} className="h-[100px] w-[90px] lg:h-auto lg:w-auto mx-2" />
        </div>
      </div>
         
      <div className='py-0 lg:flex '>
         
        <div className="lg:flex lg:flex-col lg:gap-y-8 lg:w-[54%] lg:mt-20">
          <h2 className='font-black text-3xl w-[300px] mx-auto lg:text-4xl lg:w-[360px] leading-12 tracking-wide'>Why Become An  Alison Affiliate?</h2>
          <img src={becomeanaffilatedesktop} className="hidden lg:block " />
        </div>

        <div className='max-w-[440px] mx-auto py-10 flex flex-col gap-y-5 lg:max-w-[46%] lg:mx-0 '>
          <div className="lg:m-8 lg:ml-0 lg:shadow-2xl lg:bg-[rgb(247,246,243)] lg:flex lg:flex-col lg:gap-y-5  lg:p-16 lg:rounded-3xl">
            <div>
              <div className='flex gap-x-2 font-bold'><div className='w-6 h-6 rounded-full bg-black pl-1 bg-[rgb(45,57,65)]'><FontAwesomeIcon icon={faCheck} className='text-white text-[16px]' /></div><h4 className='text-xl text-[rgb(45,57,65)]'>Quick & Free To Join</h4></div>
              <p>Join for free in under a minute. There is no application form so you can start earning immediately.</p>
            </div>
            <div>
              <div className='flex gap-x-2 font-bold'><div className='w-6 h-6 rounded-full bg-black pl-1 bg-[rgb(45,57,65)]'><FontAwesomeIcon icon={faCheck} className='text-white text-[16px]' /></div><h4 className='text-xl text-[rgb(45,57,65)]'>Earn Money & Gain Experience</h4></div>
              <p>The more learners you bring in, the more money you earn. Show off your affiliate marketing skills and start earning.</p>
            </div>
            <div>
              <div className='flex gap-x-2 font-bold'><div className='w-6 h-6 rounded-full bg-black pl-1 bg-[rgb(45,57,65)]'><FontAwesomeIcon icon={faCheck} className='text-white text-[16px]' /></div><h4 className='text-xl text-[rgb(45,57,65)]'>We’ll Help You</h4></div>
              <p>We’ll provide you with a marketing toolkit to help you spread the word about Alison.</p>
            </div>
            <div>
              <div className='flex gap-x-2 font-bold'><div className='w-6 h-6 rounded-full bg-black pl-1 bg-[rgb(45,57,65)]'><FontAwesomeIcon icon={faCheck} className='text-white text-[16px]' /></div><h4 className='text-xl text-[rgb(45,57,65)]'>Fun Features Coming Soon!</h4></div>
              <p>Unlock badges and receive points for your affiliate activity. Compete with others to be top of the leaderboard.</p>
            </div>
            <div className='bg-[rgb(249,157,39)] text-white text-md font-bold text-center mt-4 p-3 rounded-full  w-[230px] h-[50px] mx-auto lg:w-[280px]'>
              <a href="#">Become an Affiliate</a>
            </div>
          </div>
        </div>
           
        <img src={becomeanaffilate} className="mx-auto lg:hidden" />
      </div>
        
        
      <div className="bg-[rgb(254,237,215)] py-10">
        <h2 className="text-2xl font-black max-w-[300px] mx-auto text-center lg:max-w-[94%] lg:text-3xl">Earn More As An Affiliate With Alison’s Marketing Toolkit</h2>
        <div className='bg-[rgb(249,157,39)] text-white text-md font-bold text-center mt-6 p-3 rounded-full  w-[230px] h-[50px] mx-auto '>
          <a href="#">Explore Affiliate Toolkit</a>
        </div>
      </div>


      <div className="py-16 bg-[rgb(247,246,243)]">
        <h1 className="text-3xl font-black text-center mt-12 mb-20">What Makes You a Great Affiliate</h1>
        <div className="flex flex-col gap-y-4 max-w-[400px] m-auto lg:max-w-[960px] lg:flex-row lg:gap-x-10 ">
          <div className="p-auto text-center flex flex-col gap-y-3">
            <img src={socialaffiliate} className="mx-auto w-16 h-16" />
            <h4 className="font-bold text-md">You’re Active on Social Media</h4>
            <p className="text-md">Why not be rewarded for your expertise in social media by spreading the word for Alison?</p>
          </div>
          <div className="p-auto text-center flex flex-col gap-y-3">
            <img src={helpaffiliate} className="mx-auto w-16 h-16" />
            <h4 className="font-bold text-md">You Love to Help Others</h4>
            <p className="text-md">By sharing our free resources with others you can help them achieve their dreams.</p>
          </div>
          <div className="p-auto text-center flex flex-col gap-y-3">
            <img src={learningaffiliate} className="mx-auto w-16 h-16" />
            <h4 className="font-bold text-md">You Enjoy Learning at Alison</h4>
            <p className="text-md">Have you used Alison before? Then we want to thank you for being an advocate for empowerment.</p>
          </div>
        </div>
        <div className="mt-16">
          <p className="text-center font-bold">Do any of these sound like you?</p>
          <div className='bg-[rgb(249,157,39)] text-white text-md font-bold text-center mt-6 p-3 rounded-full  w-[230px] h-[50px] mx-auto '>
            <a href="#">Become an Affiliate</a>
          </div>
        </div>
      
        </div>


      </div>


    

  )
}

export default Affiliates